name: Gradle Build and SBOM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    env:
      GHCR_USERNAME: ${{ github.actor }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      IMAGE_PUSH: false # Change to true if you want to push images

    strategy:
      matrix:
        project:
          # - native
          # - normal
          - quarkus

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub (for pulling base images)
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GitHub Container Registry (for pushing final image)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ GHCR_USERNAME }}
        password: ${{ GHCR_TOKEN }}

    - name: Set up JDK 23
      if: matrix.project != 'native'
      uses: actions/setup-java@v3
      with:
        java-version: 23
        distribution: 'temurin'

    - name: Setup Buildpacks CLI
      uses: buildpacks/github-actions/setup-pack@v5.3.0
      with:
        pack-version: 0.33.2

    - uses: graalvm/setup-graalvm@v1
      if: matrix.project == 'native'
      with:
        java-version: 23
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: GraalVM image validation
      if: matrix.project == 'native'
      run: |
        echo "GRAALVM_HOME: $GRAALVM_HOME"
        echo "JAVA_HOME: $JAVA_HOME"
        java --version
        native-image --version

    - name: Grant execute permission for gradlew
      run: chmod +x ${{ github.workspace }}/gradle-parent/gradlew
      working-directory: ${{ github.workspace }}/gradle-parent/${{ matrix.project }}

    - name: Build JAR with Gradle
      if: matrix.project != 'native'
      run: ../gradlew build
      working-directory: ${{ github.workspace }}/gradle-parent/${{ matrix.project }}

    - name: Build Native Executable (only for native project)
      if: matrix.project == 'native'
      run: ../gradlew nativeCompile
      working-directory: ${{ github.workspace }}/gradle-parent/${{ matrix.project }}

    - name: Generate SBOM
      run: ../gradlew cyclonedxBom
      working-directory: ${{ github.workspace }}/gradle-parent/${{ matrix.project }}

    - name: Build Container Image for Quarkus
      if: matrix.project == 'quarkus'
      run: |
        ../gradlew imageBuild \
          -Dquarkus.buildpack.log-level=debug \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.builder=buildpack \
          -Dquarkus.container-image.push=${IMAGE_PUSH} \
          -Dquarkus.container-image.registry=ghcr.io \
          -Dquarkus.container-image.username=${GHCR_USERNAME} \
          -Dquarkus.container-image.password=${GHCR_TOKEN} \
          -Dquarkus.container-image.tag=${{ github.sha }} \
          -Dquarkus.buildpack.jvm-builder-image=docker.io/paketobuildpacks/builder-jammy-base:latest \
          -Dquarkus.buildpack.run-image=docker.io/eclipse-temurin:23-jre \
          -Dquarkus.buildpack.builder-env.BP_JVM_VERSION=23 \
          -Dquarkus.buildpack.base-registry-username=${DOCKERHUB_USERNAME} \
          -Dquarkus.buildpack.base-registry-password=${DOCKERHUB_TOKEN} \
          -Dquarkus.buildpack.log-level=debug \
          -DskipTests
      working-directory: ${{ github.workspace }}/gradle-parent/${{ matrix.project }}

    - name: Build Container Image for Spring Boot
      if: matrix.project != 'quarkus'
      run: ../gradlew bootBuildImage
      working-directory: ${{ github.workspace }}/gradle-parent/${{ matrix.project }}