name: Gradle Build and SBOM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: write

    strategy:
      matrix:
        project:
          - normal
          - quarkus
          - native

    env:
      IMAGE_PUSH: true # Change to true if you want to push images
      IMAGE_REGISTRY: ghcr.io
      IMAGE_GROUP: ${{ github.repository_owner }}
      IMAGE_NAME: java-sbom-cdx-gradle-${{ matrix.project }}
      IMAGE_TAG: ${{ github.sha }}
      # OCI Metadata
      IMAGE_AUTHOR: ${{ github.actor }}
      IMAGE_SOURCE: https://github.com/${{ github.repository }}
      IMAGE_LICENSE: Apache-2.0
      BUILDER_IMAGE_NAME: docker.io/paketobuildpacks/builder-jammy-java-tiny
      BUILDER_IMAGE_TAG: 0.0.20
      BP_JVM_VERSION: 23
      IMAGE_REGISTRY_USERNAME: ${{ github.actor }}
      IMAGE_REGISTRY_PASSWORD: ${{ secrets.GIT_ACTIONS_PAT }}
      UPLOAD_ARTIFACTS_NAME: gradle-${{ matrix.project }}-artifacts

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

      # Gradle Cache
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ matrix.project }}-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ matrix.project }}-${{ runner.os }}-

      # GraalVM Native Image Cache
    - name: Cache GraalVM native-image cache
      uses: actions/cache@v4
      if: matrix.project == 'native'
      with:
        path: ~/.native-image
        key: graalvm-${{ matrix.project }}-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          graalvm-${{ matrix.project }}-${{ runner.os }}-

      # Docker Layer Cache (for pack CLI or spring-boot:build-image)
    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: ~/.cache/buildpacks
        key: docker-layers-${{ matrix.project }}-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          docker-layers-${{ matrix.project }}-${{ runner.os }}-

    - name: Login to Docker Hub (for pulling base images)
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GitHub Container Registry (for pushing final image)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up JDK 23
      if: matrix.project != 'native'
      uses: actions/setup-java@v4
      with:
        java-version: 23
        distribution: 'temurin'

    - uses: graalvm/setup-graalvm@v1
      if: matrix.project == 'native'
      with:
        java-version: 23
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Grant execute permission for gradlew
      run: chmod +x ${{ github.workspace }}/gradle-parent/gradlew
      working-directory: ${{ github.workspace }}/gradle-parent/${{ matrix.project }}

    - name: Build JAR with Gradle
      if: matrix.project != 'native'
      run: ../gradlew --no-daemon :java-sbom-cdx-gradle-${{ matrix.project }}:build
      working-directory: ${{ github.workspace }}/gradle-parent/${{ matrix.project }}

    - name: Build Native Executable (only for native project)
      if: matrix.project == 'native'
      run: ../gradlew --no-daemon :java-sbom-cdx-gradle-${{ matrix.project }}:nativeCompile
      working-directory: ${{ github.workspace }}/gradle-parent/${{ matrix.project }}

    - name: Generate SBOM
      run: ../gradlew --no-daemon :java-sbom-cdx-gradle-${{ matrix.project }}:cyclonedxBom
      working-directory: ${{ github.workspace }}/gradle-parent/${{ matrix.project }}

    - name: Extract Version from Gradle Project
      if: matrix.project == 'quarkus'
      id: extract_version
      run: |
        VERSION=$(../gradlew --no-daemon -q properties -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false | grep "^version:" | awk '{ print $2 }')
        echo "Detected version: $VERSION"
        echo "APP_VERSION=$VERSION" >> $GITHUB_ENV
      working-directory: ${{ github.workspace }}/gradle-parent/${{ matrix.project }}

    - name: Build Container Image for Quarkus
      if: matrix.project == 'quarkus'
      run: |
        ../gradlew --no-daemon :java-sbom-cdx-gradle-${{ matrix.project }}:imageBuild \
          -DskipTests \
          --info \
          --stacktrace \
          -Dquarkus.log.level=INFO \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.builder=docker \
          -Dquarkus.docker.buildx.platform=linux/amd64 \
          -Dquarkus.container-image.push=${{ env.IMAGE_PUSH }} \
          -Dquarkus.container-image.username=${{ github.actor }} \
          -Dquarkus.container-image.password=${{ secrets.GIT_ACTIONS_PAT }} \
          -Dquarkus.docker.dockerfile-jvm-path=${{ github.workspace }}/gradle-parent/${{ matrix.project }}/src/main/docker/Dockerfile.jvm \
      working-directory: ${{ github.workspace }}/gradle-parent/${{ matrix.project }}

    - name: Build Container Image for Spring Boot (Gradle)
      if: matrix.project != 'quarkus'
      run: |
        ../gradlew --no-daemon :java-sbom-cdx-gradle-${{ matrix.project }}:bootBuildImage -DskipTests --info --stacktrace
      working-directory: ${{ github.workspace }}/gradle-parent/${{ matrix.project }}

    - name: Show current workspace (build|target)
      run: |
        echo "Workspace directory structure:"
        for d in $(find . -type d \( -name build -o -name target \) | sort); do
          echo "Showing contents of: $d"
          tree -a -L 15 -I 'tmp|resources|generated|classes|test|test-*|generated-*|spring-aot|graalvm-reachability-metadata' "$d"
        done
      working-directory: ${{ github.workspace }}/gradle-parent/${{ matrix.project }}

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.UPLOAD_ARTIFACTS_NAME }}
        path: |
          ${{ github.workspace }}/gradle-parent/${{ matrix.project }}/build/libs/**/*.jar
          ${{ github.workspace }}/gradle-parent/${{ matrix.project }}/build/**/*.sbom.json
          ${{ github.workspace }}/gradle-parent/${{ matrix.project }}/build/**/application.cdx.json
          ${{ github.workspace }}/gradle-parent/${{ matrix.project }}/build/*-dependency-cyclonedx.json
          ${{ github.workspace }}/gradle-parent/${{ matrix.project }}/build/**/*-dependency-cyclonedx.json
          ${{ github.workspace }}/gradle-parent/${{ matrix.project }}/build/native/**
          ${{ github.workspace }}/gradle-parent/${{ matrix.project }}/build/quarkus-app/**
          !${{ github.workspace }}/gradle-parent/${{ matrix.project }}/build/resources/**
          !${{ github.workspace }}/gradle-parent/${{ matrix.project }}/build/libs/**/*-plain.jar
          !${{ github.workspace }}/gradle-parent/${{ matrix.project }}/build/native/generated/
        if-no-files-found: ignore

    - name: Download Uploaded Artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.UPLOAD_ARTIFACTS_NAME }}
        path: ./extracted-artifacts
        if-no-files-found: ignore

    - name: Show extracted artifact tree
      run: tree -a -L 4 ./extracted-artifacts

    - name: Create Syft SBOM output directory
      run: mkdir -p syft

    - name: SBOM for Spring Boot JAR
      if: matrix.project == 'normal'
      uses: anchore/sbom-action@v0.18.0
      with:
        path: ./extracted-artifacts/libs
        artifact-name: ${{ env.IMAGE_NAME }}.syft.cdx.json
        format: cyclonedx-json
        exclude: "**/*.sbom.json,**/*.cdx.json,**/*dependency-cyclonedx.json"
        upload-artifact: true
        upload-release-assets: false

    - name: SBOM for Quarkus App Binaries
      if: matrix.project == 'quarkus'
      uses: anchore/sbom-action@v0.18.0
      with:
        path: ./extracted-artifacts/quarkus-app
        artifact-name: ${{ env.IMAGE_NAME }}.syft.cdx.json
        format: cyclonedx-json
        exclude: "**/*.sbom.json,**/*.cdx.json,**/*dependency-cyclonedx.json"
        upload-artifact: true
        upload-release-assets: false

    - name: SBOM for GraalVM Native Binary
      if: matrix.project == 'native'
      uses: anchore/sbom-action@v0.18.0
      with:
        file: ./extracted-artifacts/native/nativeCompile/${{ env.IMAGE_NAME }}
        artifact-name: ${{ env.IMAGE_NAME }}.syft.cdx.json
        format: cyclonedx-json
        exclude: "**/*.sbom.json,**/*.cdx.json,**/*dependency-cyclonedx.json"
        upload-artifact: true
        upload-release-assets: false

    - name: SBOM for Container Image
      uses: anchore/sbom-action@v0.18.0
      with:
        image: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_GROUP }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        format: cyclonedx-json
        artifact-name: ${{ env.IMAGE_NAME }}-container.syft.cdx.json
        upload-artifact: true
        upload-release-assets: false
        registry-username: ${{ github.actor }}
        registry-password: ${{ secrets.GIT_ACTIONS_PAT }}
