name: Maven Build and SBOM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    env:
      IMAGE_PUSH: true # Change to true if you want to push images

    strategy:
      matrix:
        project:
          # - native
          # - normal
          - quarkus

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub (for pulling base images)
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GitHub Container Registry (for pushing final image)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up JDK 23
      if: matrix.project != 'native'
      uses: actions/setup-java@v3
      with:
        java-version: 23
        distribution: 'temurin'

    - name: Setup Buildpacks CLI
      uses: buildpacks/github-actions/setup-pack@v5.3.0
      with:
        pack-version: 0.33.2

    - uses: graalvm/setup-graalvm@v1
      if: matrix.project == 'native'
      with:
        java-version: 23
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: GraalVM image validation
      if: matrix.project == 'native'
      run: |
        echo "GRAALVM_HOME: $GRAALVM_HOME"
        echo "JAVA_HOME: $JAVA_HOME"
        java --version
        native-image --version

    - name: Grant execute permission for maven
      run: chmod +x ../mvnw
      working-directory: ${{ github.workspace }}/maven-parent/${{ matrix.project }}

    - name: Build JAR with Maven
      if: matrix.project != 'native'
      run: ../mvnw package
      working-directory: ${{ github.workspace }}/maven-parent/${{ matrix.project }}

    - name: Build Native Executable (only for native project)
      if: matrix.project == 'native'
      run: ../mvnw -Pnative native:compile
      working-directory: ${{ github.workspace }}/maven-parent/${{ matrix.project }}

    - name: Generate SBOM
      run: ../mvnw cyclonedx:makeAggregateBom
      working-directory: ${{ github.workspace }}/maven-parent/${{ matrix.project }}

    - name: Show current workspace
      run: |
        echo "Workspace directory structure:"
        sudo apt-get update && sudo apt-get install -y tree
        tree -a -L 4
      working-directory: ${{ github.workspace }}/maven-parent/${{ matrix.project }}

    - name: Build Container Image for Quarkus
      if: matrix.project == 'quarkus'
      run: |
        ../mvnw quarkus:image-build \
          -DskipTests \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.builder=docker \
          -Dquarkus.container-image.push=${{ env.IMAGE_PUSH }} \
          -Dquarkus.container-image.registry=ghcr.io \
          -Dquarkus.container-image.username=${{ github.actor }} \
          -Dquarkus.container-image.password=${{ secrets.GHCR_TOKEN }} \
          -Dquarkus.container-image.group=${{ github.repository_owner }} \
          -Dquarkus.container-image.tag=${{ github.sha }} \
          -Dquarkus.docker.dockerfile-jvm-path=${{ github.workspace }}/maven-parent/${{ matrix.project }}/src/main/docker/Dockerfile.jvm
      working-directory: ${{ github.workspace }}/maven-parent/${{ matrix.project }}

    - name: Build Container Image for Spring Boot
      if: matrix.project != 'quarkus'
      run: ../mvnw spring-boot:build-image
      working-directory: ${{ github.workspace }}/maven-parent/${{ matrix.project }}