name: Maven Build and SBOM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    strategy:
      matrix:
        project:
          #- normal
          #- quarkus
          - native

    env:
      IMAGE_PUSH: true # Change to true if you want to push images
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/java-sbom-cdx-maven-${{ matrix.project }}
      IMAGE_TAG: ${{ github.sha }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub (for pulling base images)
      uses: docker/login-action@v4
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GitHub Container Registry (for pushing final image)
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up JDK 23
      if: matrix.project != 'native'
      uses: actions/setup-java@v4
      with:
        java-version: 23
        distribution: 'temurin'
        cache: 'maven'
        cache-dependency-path: |
          maven-parent/${{ matrix.project }}/pom.xml

    - uses: graalvm/setup-graalvm@v1
      if: matrix.project == 'native'
      with:
        java-version: 23
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: GraalVM image validation
      if: matrix.project == 'native'
      run: |
        echo "GRAALVM_HOME: $GRAALVM_HOME"
        echo "JAVA_HOME: $JAVA_HOME"
        java --version
        native-image --version

    - name: Grant execute permission for maven
      run: chmod +x ../mvnw
      working-directory: ${{ github.workspace }}/maven-parent/${{ matrix.project }}

    - name: Build JAR with Maven
      if: matrix.project != 'native'
      run: ../mvnw package
      working-directory: ${{ github.workspace }}/maven-parent/${{ matrix.project }}

    - name: Build Native Executable (only for native project)
      if: matrix.project == 'native'
      run: ../mvnw -Pnative native:compile
      working-directory: ${{ github.workspace }}/maven-parent/${{ matrix.project }}

    - name: Generate SBOM
      run: ../mvnw cyclonedx:makeAggregateBom
      working-directory: ${{ github.workspace }}/maven-parent/${{ matrix.project }}

    - name: Show current workspace
      run: |
        echo "Workspace directory structure:"
        sudo apt-get update && sudo apt-get install -y tree
        tree -a -L 4
      working-directory: ${{ github.workspace }}/maven-parent/${{ matrix.project }}

    - name: Build Container Image for Quarkus
      if: matrix.project == 'quarkus'
      run: |
        ../mvnw quarkus:image-build \
          -DskipTests \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.builder=docker \
          -Dquarkus.container-image.push=${{ env.IMAGE_PUSH }} \
          -Dquarkus.container-image.registry=ghcr.io \
          -Dquarkus.container-image.username=${{ github.actor }} \
          -Dquarkus.container-image.password=${{ secrets.GHCR_TOKEN }} \
          -Dquarkus.container-image.group=${{ github.repository_owner }} \
          -Dquarkus.container-image.image=java-sbom-cdx-maven-${{ matrix.project }} \
          -Dquarkus.container-image.tag=${{ github.sha }} \
          -Dquarkus.docker.dockerfile-jvm-path=${{ github.workspace }}/maven-parent/${{ matrix.project }}/src/main/docker/Dockerfile.jvm
      working-directory: ${{ github.workspace }}/maven-parent/${{ matrix.project }}

    - name: Build Container Image for Spring Boot (Maven)
      if: matrix.project != 'quarkus'
      env:
        IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ matrix.project }}
        IMAGE_TAG: latest
        IMAGE_PUSH: ${{ env.IMAGE_PUSH }}
        BUILDER_IMAGE_NAME: docker.io/paketobuildpacks/builder-jammy-java-tiny
        BUILDER_IMAGE_TAG: 0.0.20
        BP_JVM_VERSION: 23
        DOCKER_USERNAME: ${{ github.actor }}
        DOCKER_PASSWORD: ${{ secrets.GIT_ACTIONS_PAT }}
        IMAGE_REGISTRY: ghcr.io
      run: |
        ../mvnw spring-boot:build-image -DskipTests
      working-directory: ${{ github.workspace }}/maven-parent/${{ matrix.project }}