name: Maven Build and SBOM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          # - native
          # - normal
          - quarkus

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 23
      if: matrix.project != 'native'
      uses: actions/setup-java@v3
      with:
        java-version: 23
        distribution: 'corretto'

    - uses: graalvm/setup-graalvm@v1
      if: matrix.project == 'native'
      with:
        java-version: 23
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: GraalVM image validation
      if: matrix.project == 'native'
      run: |
        echo "GRAALVM_HOME: $GRAALVM_HOME"
        echo "JAVA_HOME: $JAVA_HOME"
        java --version
        native-image --version

    - name: Grant execute permission for maven
      run: chmod +x ./mvnw
      working-directory: ./maven-parent

    - name: Build JAR with Maven
      if: matrix.project != 'native'
      run: ./mvnw -pl ${{ matrix.project }} package
      working-directory: ./maven-parent

    - name: Build Native Executable (only for native project)
      if: matrix.project == 'native'
      run: ./mvnw -pl ${{ matrix.project }} -Pnative native:compile
      working-directory: ./maven-parent

    - name: Generate SBOM
      run: ./mvnw -pl ${{ matrix.project }} cyclonedx:makeAggregateBom
      working-directory: ./maven-parent

    - name: Build Container Image for Quarkus
      if: matrix.project == 'quarkus'
      run: ./mvnw -pl ${{ matrix.project }} package -Dquarkus.buildpack.jvm-builder-image=paketobuildpacks/builder:base -Dquarkus.container-image.build=true -Dquarkus.buildpack.builder=paketobuildpacks/builder:base -Dquarkus.buildpack.log-level=debug
      working-directory: ./maven-parent

    - name: Build Container Image for Spring Boot
      if: matrix.project != 'quarkus'
      run: ./mvnw -pl ${{ matrix.project }} spring-boot:build-image
      working-directory: ./maven-parent